### ISSUE TITLE
the old blackbox functions still show in blkbox help

### ISSUE THREAD

**Issue by gboris** [gboris/blkbox#12]

**Comment by zacdav** [comment]
What circumstances show this? I only see blkbox functions.
![help_files](http://i.imgur.com/K5P5od1.png)

**Comment by gboris** [comment]
clicking on the blkbox help

**Comment by zacdav** [comment]
There are no files at all that indicate this, i'd try removing BlackBox and just keeping blkbox

**Comment by zacdav** [comment]
@gboris please check if this is still an issue

**Comment by gboris** [comment]
it still is on my computer. i install it somewhere else and see how it looks
