### ISSUE TITLE
Feature importance table

### ISSUE THREAD

**Issue by gboris** [gboris/blkbox#2]
Feature importance table for each outer fold include its AUROC

--> enables FS based on AUROC as a function
venndiagramm for remaining features

**Comment by zacdav** [comment]
Current code provides FeatureTables subsection of the ncv object. This is a list of data.frames (by algorithm) that provide the feature importance of each feature in the holdouts - weighted by their holdout performance.
The new amendment will provide a long format table which represents the same information but with the importance scaled between 0-100 relatively for each algorithm. This will allow comparison between algorithms.
This table can be then summarised to show average feature importance by algorithm and then construct weighted venn diagrams.
