### ISSUE TITLE
defining seeds provides error in ncv

### ISSUE THREAD

**Issue by gboris** [gboris/blkbox#22]
blackbox_output_rf = blkboxNCV(data = dataset, labels = labels, outerfolds = 5, innerfolds = 5, Method = "GLM", AUC = 0.5, metric = c("ERR", "AUROC", "ACC","MCC","F-1"), exclude = c(2:8),seeds=c(1,2,3,4,5))
Error in blkboxNCV(data = dataset, labels = labels, outerfolds = 5, innerfolds = 5,  :
  unused argument (seeds = c(1, 2, 3, 4, 5))

**Comment by zacdav** [comment]
No support currently - have to think a bit more on this one.
Should be able to get around to it tonight, fell asleep last night.
