### ISSUE TITLE
update dependencies and include in README.md

### ISSUE THREAD

**Issue by gboris** [gboris/blkbox#3]
script to install dependencies from CRAN and bioconductor:

java development kit

R packages dependencies:

bigmemory
bigRF (install_github("aloysius-lim/bigrf"))

parrallel (still needs to be hardcoded)

Bartmachine (hardcoding: options(java.parameters="-Xmx4G") before library(bartmachine) is invoked in R other R has to be restarted

car
cluster
foreach
glmnet
grid
iterators
itertools
lattice
ggplot2
Matrix
missForest
mvtnorm
modeltools
nnet
pamr
party
randomRF
rJava
sandwich
stats
strucchange
survival
httr
e1071
zoo

**Comment by zacdav** [comment]
half of these are in, will add rest shortly

**Comment by gboris** [comment]
reshape2
tidyr",
dplyr
magrittr
Vennerable

**Comment by zacdav** [comment]
Only 1 Note to fix in check and everything is fixed.

**Comment by zacdav** [comment]
R CMD check results
0 errors | 0 warnings | 0 notes

R CMD check succeeded
