### ISSUE TITLE
BM error

### ISSUE THREAD

**Issue by gboris** [gboris/blkbox#30]
Error in FUN(X[[i]], ...) :
  object is not a Java object reference (jobjRef/jarrayRef).
Calls: blkboxNCV ... .BB_BARTM -> <Anonymous> -> t -> sapply -> lapply -> FUN
Execution halted

code
time Rscript --max-ppsize=500000 ../BlackBoxNCV.R ALO bartmachine 05 0.5
# input args from bash

args <- commandArgs(trailingOnly = TRUE)
# input1 is the type of dataset (pos, neg, gen, alo, bee, vee, iiz)

input1 = args[1]
# input2 is the id of feature selection method

input2 = args[2]
# input3 is the repitition of the prior

input3 = args[3]
# input4 is the AUC cutoff

input4 = as.numeric(args[4])
# #input5 is the memory for the java, 2000m buffer for safety
# input5 = as.numeric(args[5]) - 2000
# options(java.parameters = paste0("-Xmx",input4,"m"))
# loading packages

library(blkbox)
# read data

dataset = readRDS(file = paste0("/mnt/md2/data/analysis/ML/datasets/",input1,".rds"))
# read labels

labels =  readRDS(file = paste0("/mnt/md2/data/analysis/ML/datasets/",input1,"_labels.rds"))
# ncv function

blackbox_output = blkboxNCV(data = dataset, labels = labels, Method = input2, AUC = input4, metric = c("ERR", "AUROC", "ACC","MCC","F-1"), exclude = c(1:8)[-which(input2 == c("randomforest", "kknn", "bartmachine", "party", "GLM", "PamR", "nnet", "SVM"))], seed = 1)
# saving the object as rds

saveRDS(blackbox_output, file = paste0(input1,"_",input2,"_",input3,"_",input4,".rds"))
# this result can then be downloaded and the performance calculated locally once the object is reloaded into session
# then readRDS()
# datasets must be of name structure 3CHARNAME_#SAMPLES_#FEATURES.rds
# labels must be of name structure 3CHARNAME_labels.rds

**Comment by gboris** [comment]
can be memory related current;y testing ;locally

**Comment by gboris** [comment]
local mac it rann through but gave these erros Warning messages:
1: In ci.auc.roc(roc, ...) :
  ci.auc() of a ROC curve with AUC == 1 is always 1-1 and can be misleading.
2: In ci.auc.roc(roc, ...) :
  ci.auc() of a ROC curve with AUC == 1 is always 1-1 and can be misleading.
3: In mean.default("Importance", na.rm = T) :
  argument is not numeric or logical: returning NA

**Comment by zacdav** [comment]
its memory related. not my issue.
