### ISSUE TITLE
Fix alternate repository for suggests packages

### ISSUE THREAD

**Issue by zacdav** [gboris/blkbox#31]
Will be a bit weird because I do not have authority for bigrf to do this. We should email creator and ask him to set it up with drat + github if possible.

**Comment by gboris** [comment]
just fix the rest first. i don't get it bigrf is on github which is a main repository???

**Comment by zacdav** [comment]
Repositories are particular file structures and setups. You can use github as a repository but it is currently not set up to be one for bigrf.

https://stat.ethz.ch/pipermail/r-package-devel/2015q2/000012.html
