### ISSUE TITLE
feature selection heatmap plotting would be good to select to the desired fs method

### ISSUE THREAD

**Issue by gboris** [gboris/blkbox#48]

**Comment by gboris** [comment]
str(feature_benchmarks_wide$IIZ.0.1)
'data.frame':   6156 obs. of  7 variables:
 $ dataset    : chr  "IIZ" "IIZ" "IIZ" "IIZ" ...
 $ cutoff     : chr  "0.1" "0.1" "0.1" "0.1" ...
 $ feature    : chr  "gene1" "gene10" "gene100" "gene1000" ...
 $ bartmachine: num  0.0179 0.0131 0.0182 0.0117 0.0166 ...
 $ GLM        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ PamR       : num  0.00988 0 0 0 0 ...
 $ SVM        : num  0 0 0 0 0 0 0 0 0 0 ...

changing the number in the plot funciton solves it. ... [,5:ncol(f....

pdf(paste0("heatmaps_glm", ".pdf"), width = 7, height = 5)
for(i in 1:length(feature_benchmarks_wide)){
  pheatmap(t(as.matrix(feature_benchmarks_wide[[i]][,5:ncol(feature_benchmarks_wide[[i]])])),
           main = paste(unique(feature_benchmarks_wide[[i]]$dataset),
                        unique(feature_benchmarks_wide[[i]]$cutoff)),
           treeheight_col = 0,
           legend = F,
           fontsize_col = 0.1,
           color = brewer.pal(9,"Reds"))
}
dev.off()

**Comment by gboris** [comment]
needs a filter >0 since it otherwise utilizes all features which have a value in col 4.

**Comment by zacdav** [comment]
Each algorithm on the heatmap is a FS method, we arent using it to gauge what to use. This is comparing differences after everything is completed.
