### ISSUE TITLE
Vignette to be written

### ISSUE THREAD

**Issue by zacdav** [gboris/blkbox#6]

**Comment by gboris** [comment]
add to vignett quick installation instructions for vennerable
xquartz
source("https://bioconductor.org/biocLite.R")
biocLite(c("RBGL","graph"))
cran:
‘reshape’, ‘gtools’
install.packages("Vennerable", repos="http://R-Forge.R-project.org")

and big-rf
install_github("aloysius-lim/bigrf”)

**Comment by gboris** [comment]
- mention in method that knn doesn't allow FS
